### ISSUE TITLE
消费组这块没有，数据实际是有的

### ISSUE THREAD

**Issue by lidane2** [didi/kafka-manager#55]
ConsumerGroup列表

![image](https://user-images.githubusercontent.com/36751152/93196681-50652500-f77d-11ea-9760-68d10e88684f.png)

后台有个warning
2020-09-15 10:00:30.667  WARN 1 --- [ask-ClusterId-1] c.x.k.m.s.service.impl.JmxServiceImpl    : getSpecifiedBrokerMetricsFromJmx@JmxServiceImpl, get metrics fail, objectName:kafka.log:type=LogFlushStats,name=LogFlushRateAndTimeMs.

javax.management.InstanceNotFoundException: kafka.log:type=LogFlushStats,name=LogFlushRateAndTimeMs
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:679)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1449)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttributes(RMIConnectionImpl.java:675)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttributes(Unknown Source)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttributes(RMIConnector.java:928)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getSpecifiedBrokerMetricsFromJmx(JmxServiceImpl.java:74)
        at com.xiaojukeji.kafka.manager.service.collector.CollectBrokerMetricsTask.collect(CollectBrokerMetricsTask.java:41)
        at com.xiaojukeji.kafka.manager.service.collector.BaseCollectTask.run(BaseCollectTask.java:23)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ZQKC** [comment]
消费组：添加集群的时候，配置的集群服务地址是否正确？
日志里面的WARN：这个可以忽略，这个日志表示JMX里面没有这个指标。

**Comment by lidane2** [comment]
![image](https://user-images.githubusercontent.com/36751152/93548914-d5795580-f99a-11ea-8f38-fcf3d59ea489.png)
其他的数据都是正常的。有人看下吗？

**Comment by lidane2** [comment]
![image](https://user-images.githubusercontent.com/36751152/93548992-048fc700-f99b-11ea-874c-a289a1c626f3.png)
这个是图

**Comment by ZQKC** [comment]
配置的地址如果没有问题的话，那么重启一下试一下。然后包的话，建议使用源码打包一下，不要直接下载release包

**Comment by ZQKC** [comment]
建议在新版中再看一下，同时检查一下Topic采样是否有问题，如果Topic有数据，但是采样失败，然后这个消费组也看不到，那么估计是配置的集群服务地址有问题
