### ISSUE TITLE
mac下安装之后jmx报错

### ISSUE THREAD

**Issue by winterthinker** [didi/kafka-manager#9]
[DataCollectorManager-ScheduleTask] ERROR c.x.k.manager.service.service.impl.JmxServiceImpl - getSpecifiedBrokerMetricsFromJmx@JmxServiceImpl, get metrics fail, objectName:kafka.network:type=RequestMetrics,name=RequestsPerSec,request=FetchConsumer.
javax.management.InstanceNotFoundException: kafka.network:type=RequestMetrics,name=RequestsPerSec,request=FetchConsumer
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1083)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:671)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)

**Comment by ZQKC** [comment]
Kafka JMX上这个指标是否存在

**Comment by zhangliangboy** [comment]
Hi，这个问题修复了吗？

**Comment by yangbajing** [comment]
这个其实不算错误，应把类似 JMX 查询日志改成 warn 并不打印异常堆栈。

**Comment by ZQKC** [comment]
是的，后续我们优化一下，把InstanceNotFoundException这个异常单独捕获，不打ERROR日志，WARN的日志的话，我们看一下怎么避免打太多重复的
